### ISSUE TITLE
Personal Effort Documents

### ISSUE THREAD

**Issue by keremuslular** [bounswe/bounswe2020group7#10]
Members need to write their weekly personal efforts documents.

**Comment by darktheorys** [comment]
- [ ] @ahmetdadak

- [ ] @alperendivriklioglu

- [x] @darktheorys

- [ ] @Hryurt

- [ ] @MEHMETTEMIZEL

- [ ] @HUmutOzdemir 

- [ ] @meltemarsl 

- [ ] @ertbulbul

- [ ] @keremuslular 

- [ ] @oykuyilmaz1
