### ISSUE TITLE
Android - Register Page

### ISSUE THREAD

**Issue by ertbulbul** [bounswe/bounswe2020group7#104]
Implementation of the register page.

**Comment by darktheorys** [comment]
I have implemented the general fragmental part of this objective.
More is upcoming soon.

**Comment by darktheorys** [comment]
I have implemented the login/register page, and pushed into android-dev-lrpage branch.

**Comment by darktheorys** [comment]
I have updated the ui part, added recyclerview modals to gather info from backend.

**Comment by darktheorys** [comment]
merged with the android-dev, can be closed
details can be found in repo.
