### ISSUE TITLE
Android Retrofit Research and Implementation

### ISSUE THREAD

**Issue by darktheorys** [bounswe/bounswe2020group7#135]
Please implement and add retrofit rest api to our android application.

**Comment by ertbulbul** [comment]
I made research about retrofit. I think it would be a better practice to create retrofits as a singleton object. I also came to the conclusion that we have to do the communication between the model layer and the presenter layer through callbacks.

**Comment by darktheorys** [comment]
According to your comments, i have implemented retrofit2 to my branch called android-dev-lrpage and android-dev-lrfpage. Also, i have implemened RX-kotlin dependency to handle asyncronic communication with server.
Thank you for your comment.
