### ISSUE TITLE
Backend - Bug of PUT request of  User Endpoint 

### ISSUE THREAD

**Issue by HUmutOzdemir** [bounswe/bounswe2020group7#173]
When a request with all same values given to the PUT request it gives error. Please solve this bug, because it creates more load on the Frontend and Android.

Deadline:  08.12.2020

**Comment by ahmetdadak** [comment]
Yes, we suffered from this issue. It would be great if you can fix this bug

**Comment by alperendivriklioglu** [comment]
This issue is going to be resolved after the pull request #218 gets merged.

**Comment by alperendivriklioglu** [comment]
As @oykuyilmaz1 reported, privacy status of the user does not get updated when requested. This needs to be checked and fixed if necessary too.

**Comment by alperendivriklioglu** [comment]
This issue will be resolved after #234 gets merged.
