### ISSUE TITLE
Follower and followings lists

### ISSUE THREAD

**Issue by ahmetdadak** [bounswe/bounswe2020group7#176]
Can you provide an endpoint that takes get requests and return followers and followings list of the user ids?

**Comment by HUmutOzdemir** [comment]
I think it can be better to add this information to the existing endpoints

**Comment by cakmadam98** [comment]
Existing API's return user_id's with other informations such as name and e-mail. You only want to get user_id's, right?

**Comment by ahmetdadak** [comment]
@cakmadam98 yes, you are right, it was definitely what I mean. I would be great if you can provide it, but it is not high priority, I can handle it in frontend but it makes run website more efficient if there is such an feature also.

**Comment by HUmutOzdemir** [comment]
Add is_private and follow_state to the get user endpoints.

Deadline: @05.12.2020

**Comment by alperendivriklioglu** [comment]
This issue is the duplicate of #195, if I understand it right. So, this will be resolved after the pull request #218 gets merged.
