### ISSUE TITLE
Creating Slack Channels

### ISSUE THREAD

**Issue by Hryurt** [bounswe/bounswe2020group7#18]
- Create 3 Slack channels to determine requirement of the assignment.

**Comment by alperendivriklioglu** [comment]
I have created three Slack channels as below, for the requirements of the academic collaboration platform project to be discussed:

1. "requirements_1-4" channel is the channel where the requirements in the paragraphs from 1 to 4 to be discussed.
2. "requirements_5-8" channel is the channel where the requirements in the paragraphs from 5 to 8 to be discussed.
3. "requirements_9-12" channel is the channel where the requirements in the paragraphs from 9 to 12 to be discussed.
