### ISSUE TITLE
Milestone 1 Report - Executive Summary

### ISSUE THREAD

**Issue by cakmadam98** [bounswe/bounswe2020group7#180]
Summary of project status and any changes that are planned for moving forward.

Deadline is 29.11.2020 10:00.

**Comment by alperendivriklioglu** [comment]
Platon is an academic collaboration platform to help researchers find collaborators for their projects, follow the researchers whose work they find interesting and hear about the latest academic events. It's free to use and open to everyone.

 The project is currently at a good state, as we had more functionalities ready than the asked for the first milestone: we did not only implement the registration and the login functionalities but also the follow, notification, research information collection systems as well. Our frontend and Android teams have designed the necessary pages for each functionality too. However, there is still some work to be done to fix the few bugs in our app.

 For the upcoming milestone, we want to
- fix the currently existing bugs,
- create the "workspaces" functionality to allow our users start their research projects on our platform,
- create "activity stream" to allow our users to see the activities of the people they follow,
- increase our code coverage by increasing the number of tests
