### ISSUE TITLE
Customer Meeting Questions

### ISSUE THREAD

**Issue by HUmutOzdemir** [bounswe/bounswe2020group7#19]
Everyone writes question suggestions about the customer meeting under this issue. Suggestions will be collected at Thursday evening and added to our previous questions.

* Deadline: **@27.02.2020 23.00**

**Comment by Hryurt** [comment]
- What is basic keyword for searching? 
- Should there be an admin account?
- Should there be bots to make adjustment in the platform?

**Comment by meltemarsl** [comment]
Who can register (Only academicians?, Can students register )?
What can unregistered users do?

**Comment by meltemarsl** [comment]
Are there more than one registered user type?
Registration platforms?

**Comment by meltemarsl** [comment]
What is the content of mock up?

**Comment by oykuyilmaz1** [comment]
- Do every collaborator have the same permissions to manage a project or do they have different privileges? 

- What will the profile page include(like their previous papers/ how much info)?

-  Who creates the conferences, only academicians or are there other users? Or do we retrieve info from other websites? Are they only for general info, or will  the summary or videos be published in that page?

-  Can the plots or the codes etc. can be created in the platform or is it like moodle, only submission?

- Who can evaluate the academicians? Guests/ (if any) students. Can any comment be deleted by the profile owner?

- Are there filters in the semantic search or in any search?

- How does the recommendation system work? Do we tell the users why we matched them?

- Can users follow each other? Can they block someone?

- Do anyone 'like' or 'comment' to the projects/ papers?

**Comment by darktheorys** [comment]
* How the project management will be done? Will it be like github?( issue, wiki, ...)
* How content sharing will be done? ( Will it be like github? )
* What are the topics/events that a user able to create? Conference/journal/project etc? and who can create what type of event, and join/apply them.
* Will there be Private profile / public profile like in linkedin?
* Will user be able to connect its profile only by Google Scholar or ResearchGate?
* What will be the user types? For example: Only Academicians can create and join research papers, project management can be done by any user. Is it sth like that.

**Comment by ahmetdadak** [comment]
What exactly an academician is? Is he/she currently working a university? Should he/she work in a university or can he/she work in an instutition? Does a person with Phd degree who wants to use the app be considered a guest or academician?

Do we provide a messaging system?
Do we ask for which university they are working in while registering?

For a guest (if we have a guest), what is the main page (like recent posts, most voted)?

**Comment by keremuslular** [comment]
### Requirements

- Can guests see the profile and past publishings of registered users?

- Will our app connect to external sites/apps (Slack, Trello, etc.) for easy contribution to the research?

- Can registered users see which users looked to their profile, open and closed projects?

- Do we create an in-app communication system for registered users? (chat, calls, etc.)


### Unrelated

- How in-depth our scenarios and mockups have to be right now?

**Comment by HUmutOzdemir** [comment]
I collect all of the questions above and my questions. Also, I categorize our questions for the meeting. Questions can be found [here](https://github.com/bounswe/bounswe2020group7/wiki/Questions-of-First-Customer-Meeting)

**Comment by MEHMETTEMIZEL** [comment]
Who does set the milestones?(Who is the corresponding author?)
