### ISSUE TITLE
Uploading Meeting #3 Notes

### ISSUE THREAD

**Issue by darktheorys** [bounswe/bounswe2020group7#21]
Meeting 3 notes should be uploaded to [**wiki page**](https://github.com/bounswe/bounswe2020group7/wiki/Meeting-%233-(27.02.2020)) by using the [**template**](https://github.com/bounswe/bounswe2020group7/wiki/Meeting-Notes-Template).

* **Deadline: 02.03.2020 23.59**

**Comment by Hryurt** [comment]
Done. 29.02.2020
