### ISSUE TITLE
Private User Information Problem

### ISSUE THREAD

**Issue by Hryurt** [bounswe/bounswe2020group7#255]
When I send get user request, if the user profile is private, back-end returns just error with status of 403. In order to show private profiles name and surname I need extra information with error message. 
Information that I want:

1. Name
2. Surname
3. Profile Photo
4. Institute
5. Job

**Comment by HUmutOzdemir** [comment]
I will add this field tomorrow with the profile photo upload mechanism.

**Comment by HUmutOzdemir** [comment]
I solved this issue and deployed it to the server.
