### ISSUE TITLE
Following System Mechanism Issue

### ISSUE THREAD

**Issue by Hryurt** [bounswe/bounswe2020group7#256]
After I sent follow request to someone, I must know that I had sent follow request not to send twice. I could not find any information in documentation about issue. Is there a situation I don't know about here? Can you help me?

**Comment by HUmutOzdemir** [comment]
As far as I know, in the get user endpoint there is a field that states this information. @alperendivriklioglu have more information than me. @alperendivriklioglu am I right?

**Comment by cakmadam98** [comment]
@Hryurt you can get this information from "/auth_system/user" endpoint. Documentation is not up to date. Below is the up to date output format of "/auth_system/user". 
{ 
      "id",
      "name",
      "surname",
      "e_mail",
      "is_private",
       "following_status",
       "rate",
       "profile_photo",
       "google_scholar_name",
       "researchgate_name",
       "job",
        "institution"
 }

Output Values of Following Status:
following_status = 1 # Represents that the requester user follows the requested user.
following_status = 0 # Represents that the requester user has already sent a follow request to the requested user and it is pending.
following_status = -1 # Represents that the requester user does not follow the requested user and has not yet sent a request to follow them.


I think this'll solve your problem.

**Comment by cakmadam98** [comment]
In a private conversation, Ramazan stated if the user is private, get method does not return following status. I'll solve this issue after #258 PR is merged.

**Comment by HUmutOzdemir** [comment]
This PR is merged
