### ISSUE TITLE
Adding New User Requirements

### ISSUE THREAD

**Issue by ertbulbul** [bounswe/bounswe2020group7#30]
We need to edit user requirements by making new additions after the newly created classification.

* **Deadline: 29.02.2020 23.59**

**Comment by oykuyilmaz1** [comment]
- [ ] Ahmet Dadak

- [ ] Burak Omur

- [ ] Ramazan Yurt

- [ ] Meltem Arslan

- [ ] Kerem Uslular

**Comment by meltemarsl** [comment]
Glossary part will be completed by @Hryurt

**Comment by HUmutOzdemir** [comment]
During adding new system requirements, I added and changed some of the user requirements and I want to give information about them.

1.1.4.8, 1.1.4.9 => I made them more detailed
1.1.4.10/11/12 => These are new requirements that I added.
1.1.6.2 => I changed "extended search" to "advanced search"
2.5.5 => There is no requirement about W3C Standards and Activity Streams Protocol. SO I added this requirement

* Please check the requirements that I added or changed from your part.

**Comment by darktheorys** [comment]
Thanks for feedback, i inspected the changes and resolved the duplication issue by making a mixture. Also, Nice for you to see the lack W3C standards, we had totally forgotten it. @HUmutOzdemir

**Comment by Hryurt** [comment]
I have comleted glossary part. You can review it.

**Comment by HUmutOzdemir** [comment]
We can add these 2 requirements under nonfunctional requirements. But I can't find the true subtitle.
 * The system should work 7/24 with no more than 5% downtime. 
* The color designs of the platform will be made to improve the experience of color-blind people.

**Comment by darktheorys** [comment]
Review have been made on the things that comments pointed out.
