### ISSUE TITLE
Updating Glossary Part

### ISSUE THREAD

**Issue by darktheorys** [bounswe/bounswe2020group7#32]
Members should inspect glossary part and if necessary alter descriptions, delete/add new items.

Deadline : 08.03.2020 @ 22.59

**Comment by alperendivriklioglu** [comment]
- [ ] Ahmet Dadak
- [ ] Ahmet Dadak
- [ ] Ahmet Dadak
- [ ] Ahmet Dadak
- [ ] Ahmet Dadak

**Comment by alperendivriklioglu** [comment]
- [ ] Ahmet Dadak
- [ ] Alperen Divriklioğlu
- [ ] Burak Ömür
- [ ] Hasan Ramazan Yurt
- [ ] Mehmet Temizel
- [ ] Halil Umut Özdemir
- [ ] Meltem Arslan
- [ ] Ertuğrul Bülbül
- [ ] Kerem Uslular
- [ ] Öykü Yılmaz

**Comment by darktheorys** [comment]
Glossary part updated. Can be reached from Wiki page.
