### ISSUE TITLE
Project Name and Logo Ideas

### ISSUE THREAD

**Issue by HUmutOzdemir** [bounswe/bounswe2020group7#33]
* Comment suggestions about Project Name and Logo

**Comment by oykuyilmaz1** [comment]
- Collademics
- Acollaboration

**Comment by ahmetdadak** [comment]
Platon

**Comment by ertbulbul** [comment]
Baddies Academics

**Comment by HUmutOzdemir** [comment]
The name of the project is selected as Platon.
