### ISSUE TITLE
Android/Frontend - Permission Problem

### ISSUE THREAD

**Issue by HUmutOzdemir** [bounswe/bounswe2020group7#335]
According to the permissions of both ResearchGate and Google Scholar. We need to take the permission of the user to use their previous publication information on our website. Please add a checkbox on the Edit Profile pages to take their permission.

**Comment by darktheorys** [comment]
I have added a checbox to take permission from user. Thank you for information.

**Comment by Hryurt** [comment]
I have also added a checkbox to get user's permission.
