### ISSUE TITLE
Recent Notifications - Request

### ISSUE THREAD

**Issue by darktheorys** [bounswe/bounswe2020group7#338]
I have realized that notification endpoint "/profile/notifications" returns oldest notifications in its first page. Can you change it so that it will come in time sorted order.

**Comment by HUmutOzdemir** [comment]
I wrote this endpoint. I will solve this problem as soon as possible.

**Comment by HUmutOzdemir** [comment]
This problem is solved on PR #347.

**Comment by HUmutOzdemir** [comment]
This PR is merged.
