### ISSUE TITLE
Additional Questions about Requirements

### ISSUE THREAD

**Issue by Hryurt** [bounswe/bounswe2020group7#34]
You can write your additional questions about the requirements. @oykuyilmaz1 is going to ask these questions via Piazza.

**Comment by HUmutOzdemir** [comment]
Assume I am a Registered User without private account. When I apply for a project, can the owner of the project see my comments and ratings?

**Comment by HUmutOzdemir** [comment]
Can a user join a project when project is at development phase?

**Comment by ahmetdadak** [comment]
Are the private workspaces can be seen in the search results?

**Comment by HUmutOzdemir** [comment]
@oykuyilmaz1 Please ask the questions above. Then, we can make some changes in the Requirements, if needed.
