### ISSUE TITLE
Frontend/Android - DELETE Endpoint of Notification

### ISSUE THREAD

**Issue by HUmutOzdemir** [bounswe/bounswe2020group7#340]
In the Android application and Frontend, notifications that are seen can not be deleted. As a result, there are so many notifications. Can you add a functionality to delete these notifications?

**Comment by darktheorys** [comment]
Implemented and pushed into android-dev-uimp

**Comment by ahmetdadak** [comment]
I created a new section for notification, it can be seen in the navbar on the right top and I implemented the delete feature also. It is deployed with PR#349

**Comment by HUmutOzdemir** [comment]
Thanks for your quick response.
