### ISSUE TITLE
Frontend/Android - Notification Times

### ISSUE THREAD

**Issue by HUmutOzdemir** [bounswe/bounswe2020group7#344]
It is just my opinion but I think if we show the creation date of notifications it can be better. Can you also show the creation date of notifications on UI. If you want I can format the format of the value returned from `/profile/notifications` endpoint.

**Comment by darktheorys** [comment]
Implemented and pushed into android-dev-uimp.

**Comment by ahmetdadak** [comment]
Frontend also provides the date of notifications. PR#340 solves the issue.

**Comment by HUmutOzdemir** [comment]
Thanks for your quick response.
