### ISSUE TITLE
Frontend - File System Show File Bug

### ISSUE THREAD

**Issue by HUmutOzdemir** [bounswe/bounswe2020group7#359]
When I tried to view a file in the deployed frontend. I see an interesting response. In the edit part, it shows the real content of the file. But when I used the view button it did not give me the correct file content. I will also share the photo of the bug.

![Bug](https://user-images.githubusercontent.com/44067662/103095814-02c94580-4613-11eb-997c-9d1a2817854f.jpg)

**My token:** eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwaXJlX3RpbWUiOiIyMDIxLTEyLTI0VDE1OjAwOjQ0LjQ3Mzc5OCJ9.clnHUO2G3-xiYBGNulObFTEKPBj4Tq6RecSptoAprwU
**Workspace ID:** 2 / Frontend WS
**The file that I tried:** fronttan_dunyaya.txt

**Real File Content:**

> Ne sarayda 
> ne handa 
> bir zalim ocaginda
>  sevdam agliyor
> Ne gam olsem ugrunda 
> beni zehir zembelek
>  diller dagliyor 
> Sertab Erener

**Comment by ahmetdadak** [comment]
I fixed the bug and deployed after #365. I checked a few scenarios for not only file preview but also all other features of the file system. I did not encounter any bugs for now but it might be some. Please check also the other features and let me know if you find further bugs. Thank you for the information.

**Comment by HUmutOzdemir** [comment]
I also rechecked this bug and I see that it was solved. Thank you for your quick response.
