### ISSUE TITLE
Frontend - Notification Bug

### ISSUE THREAD

**Issue by HUmutOzdemir** [bounswe/bounswe2020group7#360]
I found a bug in the delete functionality of the notifications of the frontend. When I deleted all the notifications on the first page, It does not refresh the notifications. But if I do the same thing on other pages, it works correctly. I am sorry, I can not give you a photo of the bug..

**Comment by ahmetdadak** [comment]
I fixed the bug and deployed after #365. It should work now. Let me know if you find any other bugs. Thank you for the information.

**Comment by HUmutOzdemir** [comment]
Thank you for your quick response. I checked it also.
