### ISSUE TITLE
Frontend - Upcoming Events Widget Bug

### ISSUE THREAD

**Issue by HUmutOzdemir** [bounswe/bounswe2020group7#361]
When I try to load new pages in the upcoming events part of our frontend, It does not delete the previous object while it is trying to fetch the new page. The following image is an example of this bug.
![Bug](https://user-images.githubusercontent.com/44067662/103103228-c99fce00-4630-11eb-962c-bc330296f4a5.jpg)

**Comment by uvut** [comment]
Fixed.

Upcoming items component will not be visible if state is fetching.
