### ISSUE TITLE
Backend - Workspace Semantic Search Improvements

### ISSUE THREAD

**Issue by HUmutOzdemir** [bounswe/bounswe2020group7#367]
This version of the semantic search of workspaces is enough to present it on the Customer Milestone 2. But I think semantic workspace search can also search the search query on related skills, requirements of the workspace, and related upcoming events of the workspace. As a result, can you improve the Workspace Semantic Search after Customer Milestone 2?

**Comment by cakmadam98** [comment]
I couldn't find time to improve workspace search. I'll focus on the final deliverables for the last days of the course. Therefore, I'm closing this issue.
