### ISSUE TITLE
Bug - Backend - Search User with Sorting

### ISSUE THREAD

**Issue by darktheorys** [bounswe/bounswe2020group7#370]
I have faced with internal server error (500) while using the sorting option in user search. Below i have provided the case where i encountered with the bug.

There is all the fieds that i have filled. In my opinion, i should have get a 4xx error, if i am wrongly doing something.

- path=http://18.185.75.161:5000/api/search_engine/user
- query = "bur"
- sorting_criteria=0
- page=0
- per_page=10
- token=
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NCwiZXhwaXJlX3RpbWUiOiIyMDIxLTEyLTI1VDIyOjQzOjIxLjY3NDM1NyJ9.mL-4y-yH9mjH1xYpA9RNugkpWCTaffVYnJhTi9Krpoo

**curl -X GET "http://18.185.75.161:5000/api/search_engine/user?search_query=bur&sorting_criteria=0&page=0&per_page=10" -H "accept: application/json" -H "auth_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NCwiZXhwaXJlX3RpbWUiOiIyMDIxLTEyLTI1VDIyOjQzOjIxLjY3NDM1NyJ9.mL-4y-yH9mjH1xYpA9RNugkpWCTaffVYnJhTi9Krpoo"**

**Comment by HUmutOzdemir** [comment]
It is fixed
