### ISSUE TITLE
Revision of the Requirements

### ISSUE THREAD

**Issue by oykuyilmaz1** [bounswe/bounswe2020group7#40]
The changes I made after the feedback can be found here: https://github.com/bounswe/bounswe2020group7/wiki/ReqAfterFeed

Please check them. Also please check the feedback page and change the requirements according to the feedback, the ones I did not change have question marks under them.
https://github.com/bounswe/bounswe2020group7/wiki/feedback
@HUmutOzdemir @darktheorys @ahmetdadak @keremuslular 

And could any of you please revert the requirements back to the version which we did not have to click that much? Please make your changes in the page named ReqAfterFeed
https://github.com/bounswe/bounswe2020group7/wiki/ReqAfterFeed
@ertbulbul @meltemarsl @alperendivriklioglu

**Comment by HUmutOzdemir** [comment]
I made some changes. But still, there are some feedbacks that I cannot find a way to correct our Requirements document. I can not understand that if we make an explanation in the glossary, still we have to write a detailed explanation of it in the requirements.

**Comment by darktheorys** [comment]
Updated feedback and reqAfterFeed. Please check for further necessities.

**Comment by oykuyilmaz1** [comment]
I updated the 2 requirements we discussed in the meeting and good news- no more clicking!

**Comment by HUmutOzdemir** [comment]
I changed the profile page part of our requirements according to its feedback. It can be found in the reqAfterFeed document.

**Comment by oykuyilmaz1** [comment]
Our Requirements are now under the link: https://github.com/bounswe/bounswe2020group7/wiki/Project-Requirements
I deleted the feedback page and the previous requirements page.
