### ISSUE TITLE
Sequence Diagram Preparation

### ISSUE THREAD

**Issue by MEHMETTEMIZEL** [bounswe/bounswe2020group7#41]
Should be prepared and published.

**Comment by HUmutOzdemir** [comment]
I added Workspace Creation and Link ResearchGate and Google Scholar Account diagrams to the [sequence diagrams document](https://github.com/bounswe/bounswe2020group7/wiki/Sequence-Diagrams). Please check it and give feedback if there is a mistake in the diagrams.

**Comment by darktheorys** [comment]
Notification Creation and Keyword Search with Sorting added. Review is suggested.

**Comment by oykuyilmaz1** [comment]
Comment rate diagram is ready. Please review it.

**Comment by ahmetdadak** [comment]
View Activity Stream sequence diagram is added as 5th sequence diagram page. It seems a bit short to me, please review it.

**Comment by keremuslular** [comment]
Inviting User to Workspace is added as the 9th diagram.

**Comment by keremuslular** [comment]
> Inviting User to Workspace is added as the 9th diagram.

Considering Inviting a User to Workspace and Responding to an Invitation are two separate use cases, I've divided the earlier sequence diagram into two separate diagrams. You can find them as the 9th and 10th in [here](https://github.com/bounswe/bounswe2020group7/wiki/Sequence-Diagrams).
