### ISSUE TITLE
Design Documents Feedback Update(Use Case Diagram)

### ISSUE THREAD

**Issue by HUmutOzdemir** [bounswe/bounswe2020group7#42]
Update the use case diagram according to the feedback given [here](https://github.com/bounswe/bounswe2020group7/wiki/Design-Documents-Feedback). Then, write all updates to the feedback document which can be found [here](https://github.com/bounswe/bounswe2020group7/wiki/Design-Documents-Feedback)

Deadline: @@

**Comment by darktheorys** [comment]
To clarify, It had been finished almost a week ago. 
Can be found [**here**](https://github.com/bounswe/bounswe2020group7/wiki/Use-Case-Diagrams)
