### ISSUE TITLE
Frontend - Issue comment section

### ISSUE THREAD

**Issue by ahmetdadak** [bounswe/bounswe2020group7#428]
There are some issues related to the comment part of the issue section. There is a blue button that shows the comments part. When it is clicked for the first time, nothing happens but after the first time it is clicked, it is loading the comments. It should show when it is clicked for the first time. Also, an issue's comments should be fetched after deletion or creation of a comment.
Note that I've tried to make a collapsable part for comments but the design could be change also.

**Comment by uvut** [comment]
Fixed with [this commit](https://github.com/bounswe/bounswe2020group7/commit/b5e7cca6b2d3c91090d1f9e017513407ba293cdf)
