### ISSUE TITLE
Additional fields needed on GET /follow/comment endpoint

### ISSUE THREAD

**Issue by uvut** [bounswe/bounswe2020group7#435]
I need **profile_photo, name, surname** information of **COMMENTER** to be added to _GET /follow/comment_ endpoint for [Ratings Feature PR](https://github.com/bounswe/bounswe2020group7/pull/434) 

Example response:

```js
{
  "number_of_pages": 0,
  "result": [
    {
      "comment_id": 0,
      "owner_id": 0,
      "owner_name": string, // to be added
      "owner_surname": string, // to be added
      "owner_profile_photo": string, // to be added
      "commented_user_id": 0,
      "timestamp": "2021-01-17T12:40:48.014Z",
      "rate": 0,
      "text": "string"
    }
  ]
}
```

**Comment by HUmutOzdemir** [comment]
I can add these fields as soon as possible. Thanks for your comment.

**Comment by HUmutOzdemir** [comment]
I added these features. You can see them on PR #455. These changes will be deployed when this PR is merged.
