### ISSUE TITLE
Design Documents Feedback Update(Sqeuence Diagram)

### ISSUE THREAD

**Issue by HUmutOzdemir** [bounswe/bounswe2020group7#44]
Update your own sequence diagram according to the feedback given [here](https://github.com/bounswe/bounswe2020group7/wiki/Design-Documents-Feedback). Then, write all updates to the feedback document which can be found [here](https://github.com/bounswe/bounswe2020group7/wiki/Design-Documents-Feedback)

- [x] Halil Umut Özdemir
- [x] Öykü Yılmaz
- [ ] Alperen Divriklioğlu 
- [x] Burak Ömür 
- [x] Ertuğrul Bülbül 
- [x] Mehmet Temizel 
- [x] Hasan Ramazan Yurt 
- [x] Ahmet Dadak
- [x] Kerem Uslular
- [x] Meltem Arslan 

Please mark them when you finish your updates and the last person that updates the sequence diagram will close the issue.

Deadline: @@

**Comment by HUmutOzdemir** [comment]
I updated my sequence diagrams which are Workspace Creation and Link ResearchGate and Google Scholar Accounts. The updates can be found [here](https://github.com/bounswe/bounswe2020group7/wiki/Sequence-Diagrams)

**Comment by oykuyilmaz1** [comment]
I changed the comment-rate diagram according to the feedback.

**Comment by ertbulbul** [comment]
I modified the send collaboration request diagram according to the given feedback.

**Comment by meltemarsl** [comment]
I deleted milestone.insert(milestone) message according to feedback-2.

**Comment by ahmetdadak** [comment]
I modified the view activity stream according to the feedback

**Comment by MEHMETTEMIZEL** [comment]
I uploaded the reorganized the advanced filtered search according to feedback that.

**Comment by HUmutOzdemir** [comment]
Update your own sequence diagram according to the feedback given [here](https://github.com/bounswe/bounswe2020group7/wiki/Design-Documents-Feedback) and given in the lectures. Then, write all updates to the feedback document which can be found [here](https://github.com/bounswe/bounswe2020group7/wiki/Design-Documents-Feedback)

- [ ] Halil Umut Özdemir
- [ ] Öykü Yılmaz
- [ ] Alperen Divriklioğlu 
- [ ] Burak Ömür 
- [ ] Ertuğrul Bülbül 
- [ ] Mehmet Temizel 
- [ ] Hasan Ramazan Yurt 
- [ ] Ahmet Dadak
- [ ] Kerem Uslular
- [ ] Meltem Arslan 

Please mark them when you finish your updates and the last person that updates the sequence diagram will close the issue.

Deadline: @ 23.59 13.06.2020

**Comment by HUmutOzdemir** [comment]
I updated Workspace Creation, Link Research Gate Account and Link Google Schılar Account sequence diagrams. New diagrams can be found on the wiki page.

**Comment by darktheorys** [comment]
Basic keyword search and notification sequence diagrams are updated according to feedback. Use case diagram is also updated already.

**Comment by MEHMETTEMIZEL** [comment]
Advanced filtered search diagram is updated and you can see it on the wiki page.

**Comment by ahmetdadak** [comment]
View activity page diagram is removed and file creation diagram is updated.

**Comment by ertbulbul** [comment]
Send collaboration request diagram is updated.

**Comment by keremuslular** [comment]
Inviting a User to Workspace and Responding to an Invitation sequence diagrams are updated according to the latest feedback.
