### ISSUE TITLE
Frontend -  Implementation of missing requirements

### ISSUE THREAD

**Issue by Hryurt** [bounswe/bounswe2020group7#440]
Implementation of some missing requirements after milestone 2.

- [x] Guest search
- [x] Add link to upcoming events section
- [x] Report user

**Comment by Hryurt** [comment]
Add link to upcoming events section is implemented by @ahmetdadak

**Comment by ahmetdadak** [comment]
Add link to upcoming events section is solved with #443

**Comment by Hryurt** [comment]
Implemented and merged.
