### ISSUE TITLE
Frontend - Profile Page Direction Not Working

### ISSUE THREAD

**Issue by oykuyilmaz1** [bounswe/bounswe2020group7#469]
When the user is on someone else's profile, and tries to go to their own, they cannot. Can you fix the problem?

**Comment by ahmetdadak** [comment]
Thank you for your information. Solved with #468

**Comment by ahmetdadak** [comment]
Thank you for your information. I've just seen the problem as well. I'll figure it out.

**Comment by ahmetdadak** [comment]
Solved with #468
