### ISSUE TITLE
API Ideas

### ISSUE THREAD

**Issue by HUmutOzdemir** [bounswe/bounswe2020group7#50]
Write the ideas about the practice-app API under this issue.

Deadline: @22.00 30.04.2020

**Comment by keremuslular** [comment]
[Skyscanner API](https://skyscanner.github.io/slate/)
We can use this API to get all the flights to or from a location.

**Comment by MEHMETTEMIZEL** [comment]
[It](https://collectapi.com/tr/) gives us some ideas about API

**Comment by ahmetdadak** [comment]
We can use [MusixmatchAPI](https://developer.musixmatch.com/documentation) and [SpotifyAPI](https://developer.spotify.com/documentation/web-api/) to show the lyrics of the song that users listen to from Spotify.

**Comment by ertbulbul** [comment]
We can use  [Twitter Standard search API](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets) to show tweets about our application.

**Comment by HUmutOzdemir** [comment]
This [API](https://www.datamuse.com/api/) is a word-finding query engine. We can use this API if we add a search mechanism to our practice-app.
