### ISSUE TITLE
IDE: VS CODE

### ISSUE THREAD

**Issue by MEHMETTEMIZEL** [bounswe/bounswe2020group7#51]
Download Vs Code.
Deadline: 01.05.2020 23.59

**Comment by keremuslular** [comment]
Download Visual Studio Code [here](https://code.visualstudio.com/Download).

**Comment by keremuslular** [comment]
Useful extensions for VS Code:

- [Github](https://marketplace.visualstudio.com/items?itemName=KnisterPeter.vscode-github)

- [open in browser](https://marketplace.visualstudio.com/items?itemName=techer.open-in-browser)

- [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense)

- [Djaneiro](https://marketplace.visualstudio.com/items?itemName=thebarkman.vscode-djaneiro) or [Django](https://marketplace.visualstudio.com/items?itemName=batisteo.vscode-django)

- [REST client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)

- [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer)

- [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

- [Git Graph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph)

- [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)

- [Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare)

- [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager)

- [Regex Previewer](https://marketplace.visualstudio.com/items?itemName=chrmarti.regex)

- [Visual Studio IntelliCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode)

**Comment by MEHMETTEMIZEL** [comment]
> Useful extensions for VS Code:
> 
> * [Github](https://marketplace.visualstudio.com/items?itemName=KnisterPeter.vscode-github)
> * [open in browser](https://marketplace.visualstudio.com/items?itemName=techer.open-in-browser)
> * [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense)
> * [Djaneiro](https://marketplace.visualstudio.com/items?itemName=thebarkman.vscode-djaneiro) or [Django](https://marketplace.visualstudio.com/items?itemName=batisteo.vscode-django)
> * [REST client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)
> * [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer)
> * [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
> * [Git Graph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph)
> * [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)
> * [Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare)
> * [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager)
> * [Regex Previewer](https://marketplace.visualstudio.com/items?itemName=chrmarti.regex)
> * [Visual Studio IntelliCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode)

I've already had VS Code and I downloaded some extensions above.

**Comment by meltemarsl** [comment]
Done
