### ISSUE TITLE
JavaScript vs Python

### ISSUE THREAD

**Issue by keremuslular** [bounswe/bounswe2020group7#52]
This is a discussion issue to determine the programming language we will use for our practice-app. Please comment underneath if you have a preference and explain why.

Deadline: @22.00 01.05.2020

**Comment by meltemarsl** [comment]
does't matter for me :)

**Comment by HUmutOzdemir** [comment]
I prefer Javascript but I don't have a good reason. So, it is suitable for me to use Python too.

**Comment by keremuslular** [comment]
I personally would prefer using Python as I’m a little bit more experienced with it, but I’m not %100 proficient with either of them so it’s not a fixed choice.

**Comment by MEHMETTEMIZEL** [comment]
I prefer Javascript becasuse I want to learn that language with my team, I think I can learn Python with myself.

**Comment by ahmetdadak** [comment]
Both are the same for me. I prefer the one that will be the most voted.

**Comment by ertbulbul** [comment]
It doesn't matter to me either.

**Comment by oykuyilmaz1** [comment]
It is no problem for me either but to increase the number of votes, I will vote for JavaScript.

**Comment by Hryurt** [comment]
I prefer Python because I think implementing in Python and learning Python is easier .

**Comment by alperendivriklioglu** [comment]
I also prefer Python as it can be learnt quickly and I have more experience in developing software with Python.

**Comment by meltemarsl** [comment]
Conclusion : Python
