### ISSUE TITLE
Milestone Report 1: A summary of work done by each team member

### ISSUE THREAD

**Issue by oykuyilmaz1** [bounswe/bounswe2020group7#53]
Please list your work regarding the project under this issue by 03.05.2020 @ 15.00.

**Comment by Hryurt** [comment]
I created and edited README.md page of the group. I organized glossary part of the requirements. I helped review and regulate the requirements I was in the team preparing 1/3 of the user scenarios and mockups and we created Workspace Creation scenario and its mock-up. I was also in the team preparing class diagram; therefore, I played an active role in creating class diagrams. I prepared a sequence diagram which is named as create an issue. I was assigned to the team that planned the rest of the CMPE 352. As a team, we planned the rest and finalized Gantt Chart by entering information that is came from other teams.

**Comment by darktheorys** [comment]
Up to know, I have made many researches to make rapid proceed in project. I have helped to create user requirements, one mockup scenario, and reviewed them according to given feedback. I have helped to create use case diagram and created 2 sequence diagrams, also reviewed them according to feedback. I have helped to create project plan document, and review according to feedback. I have helped to decide which API to implement for further use.

**Comment by keremuslular** [comment]
I made minor improvements on the README file, including the addition of the group photo. I was part of the sub-group that prepared one-third of the initial requirements then I updated the user requirements and took part in the final review according to the feedback received. I helped determine the characteristics of one of the scenarios. I also assisted in the creation of the class diagram and prepared two sequence diagrams of my own(Inviting User to Workspace - Responding to an Invitation). Then I took part in the preparation of the project plan for the upcoming semester(CMPE451), reviewed the Gantt chart as a whole, and gave feedback. Finally, I made multiple suggestions for API implementations in our upcoming practice-app.

**Comment by meltemarsl** [comment]
As an orientation a repository research was done and selected repositories were added to favorite repositories page. Requirements were created according to the customer meeting. Arrangements made on the non-functional and user requirements. Contribution was made to creation of the Scenario#3 and Mockup#3. Editing some parts of wiki page has been provided. The use case diagram was created with the assigned subgroup. The sequence diagram named "Milestone Creation" was created. The 451 part of the project plan was prepared with related subgroup. The RAM was prepared according to the final version of the project plan. Corrections were made according to the feedback given in all studies. The work of other groups was reviewed in subgroup studies.

**Comment by HUmutOzdemir** [comment]
* In the first homework a repository and git research was done. 

* For the requirements, I created some requirements for the last part of the project PDF. I made a research about GDPR and KVKK, also a summary of this research was documented by me.

* I added some questions for the customer meeting and also I organized the questions of the customer meeting.

* After the customer meeting all requirements are updated and reviewed.

* I was in the team preparing 1/3 of the user scenarios and mockups and we created Workspace Creation scenario and its mock-up. Also, we updated the mockups according to the feedback as a group.

* I was in the team that creates the class diagram. Also after the feedback in the lecture and from piazza, I updated the class diagram of the group according to feedbacks.

* I made 3 sequence diagrams which are Workspace Creation, Link ResearchGate Account, and Link Google Scholar Account. Also, I review some of the sequence diagrams.

* I was a part of the group that makes the CMPE 451 part of the project plan.

* I have helped to decide which API to implement for further use.
