### ISSUE TITLE
Practice App - User Deletion

### ISSUE THREAD

**Issue by oykuyilmaz1** [bounswe/bounswe2020group7#57]
Implementation of the user deletion functionality of **practice-app**.
- [x] Implementation of the Code
- [x] Documentation
- [x] Endpoint Documentation
- [x] Unit Tests

**Comment by oykuyilmaz1** [comment]
I think this will be too complicated for the practice-app, should we consider building another endpoint?

**Comment by oykuyilmaz1** [comment]
Actually the exact problem is I can make users sign up with their Google account but since we need a token when they log in, and also we require extra information for them to sign up, this API gets too complex. I did not want to push it here but you can check the code I  was working on from my github account using this link: https://github.com/oykuyilmaz1/352_google

**Comment by HUmutOzdemir** [comment]
I made a small research about how to implement a registration with Google mechanism. I also think that it is too complicated for practice-app. I think you can change your endpoint. You can make delete user endpoint. Is this suitable for you?

**Comment by oykuyilmaz1** [comment]
First, thanks for your quick response.
That is sure suitable but I will require extra hours, is it OK if I push my work by morning?

**Comment by HUmutOzdemir** [comment]
I think it is OK. But try to finish as soon as possible.

**Comment by oykuyilmaz1** [comment]
I pushed the delete user API and also added a small feature, it returns a book recommendation for the user who deletes their account

**Comment by oykuyilmaz1** [comment]
I finished the endpoint

**Comment by HUmutOzdemir** [comment]
I created a MySQL instance on AWS. I will share its connection information on the next meeting.
