### ISSUE TITLE
Practice App - Search

### ISSUE THREAD

**Issue by oykuyilmaz1** [bounswe/bounswe2020group7#58]
Implementation of the search functionality of **practice-app**.
- [x] Implementation of the Code
- [x] Documentation
- [x] Endpoint Documentation
- [x] Unit Tests

**Comment by HUmutOzdemir** [comment]
I created the first version of the user search endpoint. Also, I created a sample unit test for search. The search endpoint has job and field of study filters, also can search users with a search string. I will add sorting functionality to this endpoint. 

It also runs on the local database.

First version of the source code can be found on practice-app-search branch.

**Comment by HUmutOzdemir** [comment]
I finished the implementation of the search module. It also includes a unit test. Everyone can test the module with this unit test.

**Comment by HUmutOzdemir** [comment]
I added HTML and Markdown Documentation of the search module, it can be found [here](https://github.com/bounswe/bounswe2020group7/tree/practice-app-search/practice-app/platon_api/rest_api/search_engine/documentation)

**Comment by HUmutOzdemir** [comment]
I finished the implementation of the search module. It also includes a unit test. Everyone can test the module with this unit test.

Also I created a pull request please check unit tests before the merge operation.

**Comment by HUmutOzdemir** [comment]
The requirements.txt is added to the practice-app-search branch. It includes all modules that I used to implement the search part. I also made some small changes about the JOB LIST API(To fetch jobs of users from an external API). I will update the documentation of the code until this night.

**Comment by HUmutOzdemir** [comment]
I updated the documentation of the search engine after the changes that I said above. Documentation can be found on the practice-app-search branch.

Also I added a small error handling part to my code.

**Comment by HUmutOzdemir** [comment]
I created a MySQL instance on AWS. I will share its connection informational on the next meeting.
