### ISSUE TITLE
Endpoint Documentation

### ISSUE THREAD

**Issue by HUmutOzdemir** [bounswe/bounswe2020group7#66]
Please add the documentation of your endpoint [here](https://github.com/bounswe/bounswe2020group7/wiki/API-Endpoint-Documentation)
- [x] Halil Umut Özdemir
- [x] Öykü Yılmaz
- [x] Alperen Divriklioğlu 
- [x] Burak Ömür 
- [x] Ertuğrul Bülbül 
- [x] Mehmet Temizel 
- [x] Hasan Ramazan Yurt 
- [x] Ahmet Dadak
- [x] Kerem Uslular
- [x] Meltem Arslan 

Deadline : @23.59 16.05.2020

**Comment by darktheorys** [comment]
I have shared a document in given page, please check my unwise documentation.

**Comment by HUmutOzdemir** [comment]
I shared documentation of the search endpoint. It can be found in the document above.

**Comment by HUmutOzdemir** [comment]
I also added the documentation of the whole code. It can be found [here](https://github.com/bounswe/bounswe2020group7/tree/practice-app-search/practice-app/platon_api/rest_api/search_engine/documentation).

**Comment by oykuyilmaz1** [comment]
https://github.com/bounswe/bounswe2020group7/wiki/API-Endpoint-Documentation
I created drafts for everyone from @HUmutOzdemir 's documentation. Please adjust your parts accordingly.

**Comment by MEHMETTEMIZEL** [comment]
I reorganized the draft Forgot Password Endpoint Documentation according to my endpoint.

**Comment by ahmetdadak** [comment]
Added into provided link

**Comment by keremuslular** [comment]
Completed my documentation and added it to the provided page link.

**Comment by alperendivriklioglu** [comment]
I added the documentation of "logout" endpoint to the document in the first comment.

**Comment by meltemarsl** [comment]
I wrote endpoint documentation for my api Update User

**Comment by meltemarsl** [comment]
Done.
