### ISSUE TITLE
Assignment 1 research doc

### ISSUE THREAD

**Issue by keremuslular** [bounswe/bounswe2020group7#7]
Create a research document for Assignment 1.

**Comment by HUmutOzdemir** [comment]
I created my research documents for Assignment 1. The documents can be found in the following links: 
* [GitHub Repository Research](https://github.com/bounswe/bounswe2020group7/wiki/Halil-Umut-%C3%96zdemir-Repository-Research)
* [Git Research](https://github.com/bounswe/bounswe2020group7/wiki/Halil-Umut-%C3%96zdemir-Git-Research
)

**Comment by MEHMETTEMIZEL** [comment]
You can find my researches in my personal wiki page.
