### ISSUE TITLE
Review Requirements

### ISSUE THREAD

**Issue by oykuyilmaz1** [bounswe/bounswe2020group7#92]
Review the requirements. Everyone should leave a comment under this issue mentioning the requirements that they think should be updated or removed. Please mark your name after you comment.

- [x] Halil Umut Özdemir  

- [x]  Hilal Demir  

- [x]  Ertuğrul Bülbül   

- [x] Ahmet Dadak  

- [x]  Hasan Ramazan Yurt 

- [x]  Burak Ömür 

- [x]  Burhan Can Akkuş 

- [x] Öykü Yılmaz 

- [x]  Hüseyin Can Bölükbaş 

- [x]  Alperen Divriklioğlu 

- [x]  Orkan Akisu 

- [x]  Umutcan Uvut

**Comment by darktheorys** [comment]
### Below, i have provided some requirements that i think we can omit while implementing Platon.

___

### 1.1 User Requirements

**1.1.1 Guests and Registration**

> 1.1.1.6 Guests shall be able to see trending projects.

**1.1.3 User Follow & Rating**

> 1.1.3.1 Users shall be able to follow public accounts.
> 
> 1.1.3.2 Users shall be able to send requests to follow private accounts.
> 
> 1.1.3.3 Users with private accounts shall be able to accept/reject follow requests.

**1.1.5 Profile Management**

> 1.1.5.5 Users shall be able to view private profiles that they are following.
> 
> 1.1.5.6 Users shall be able to mute all of the notifications.
> 
> 1.1.5.7 Users shall be able to view sections as followers, comments, ratings, photo, name and e-mail in a profile.
> 

### 1.2 System Requirements

**1.2.1 System**

> 1.2.1.1 System shall provide a site map to navigate the users.
> 
> 1.2.1.5 System shall provide profile recommendations for new people to follow.
> 

**1.2.3 Recommendation**

> 1.2.3.3 Recommendation system shall recommend appropriate projects for the interests and technical suitability to Users.
> 

**1.2.4 Notification - >> can be converted to e-mail notifications??**

> 1.2.4.1 The system should send notifications to users when new conferences have been added.
> 
> 1.2.4.2 The system shall send notifications when the user has new followers or follow requests.
> 
> 1.2.4.3 The system shall send notifications when a user gets a new comment or rating.
> 
> 1.2.4.4 The system should send notifications to the user when he/she gets accepted for collaboration from a project.
> 
> 1.2.4.5 The system should send notifications to the collaborators of the workspace when any application for collaboration request is sent to that workspace.
> 
> 1.2.4.6 The system should send notifications to the collaborators of the workspace when a deadline for any assigned issue is closed.
> 

### 2. Non-Functional Requirements


**2.1 Performance & Reliability**

> 2.1.1 System shall respond in at most 3 seconds.
> 
> 2.1.2 Search shall give result in at most 5 seconds.
> 
> 2.1.3 The system should work 7/24 with no more than 1% downtime.
> 

**2.2 Security**

> 2.2.3 System objects shall be encrypted with MD5.
> 
> 2.2.4 System shall be backed up to AWS at the end of each day.
> 

**2.3 Portability**

> 2.3.6 Mobile Browsers shall redirect to the mobile application.

**2.5 Implementation**

> 2.5.4 The color designs of the platform will be made to improve the experience of color-blind people.

**Comment by BurhanAkkus** [comment]
### These are my comments about the possible modifications on project requirements.

___

### 1.1 User Requirements

**1.1.4.6 User Follow & Rating**

> 1.1.4.2 Users shall be able to invite users to the workspace at Search for Collaborators State.
 - I think users should only be able to invite public users and private users whom they follow.
> 1.1.4.5 Collaborators of the workspace shall be able to accept/reject join requests to their workspaces.
- Allowing every collaborator to give access might be problematic. There should be a single admin user for each workspace and only that user should be able to accept/reject invites
> 1.1.4.14 Collaborators shall be able to change the state of the workspace.
- Only the admin of the workspace should be able to change the state of a workspace.
> 1.1.4.15 Collaborators shall be able to be link the workspace to an upcoming event in the system.
- I am not sure if this requirement is worded correctly. I couldn't understand it.

### 1.2 System Requirements

**1.2.1 System**

> 1.2.1.1 System shall provide a site map to navigate the users.
 - We can remove this requirement.

**Comment by cakmadam98** [comment]
> 1. Account Information: Name, surname, e-mail and affinities are necessary information. Profile photo, research, ResearchGate, and Google Scholar accounts are optional information.

> 1.1.1.1 Guests shall be able to register by providing account information which includes name, surname, e-mail, and optionally affinities, profile photo, past research, ResearchGate, and Google Scholar accounts.

- First quotation is from the glossary part. It is stated that affinities are necessary. On the other hand, affinities are stated as optional in the second quotation which is from requirements.  

> 1.1.1.6 Guests shall be able to see trending projects.

- We can omit this requirement to reduce project complexity since it is not stated in the project description or in customer meeting 1 notes.

> 1.1.5.6 Users shall be able to mute all of the notifications.

> 1.2.4.1 The system should send notifications to users when new conferences have been added.

> 1.2.4.2 The system shall send notifications when the user has new followers or follow requests.

> 1.2.4.3 The system shall send notifications when a user gets a new comment or rating.

> 1.2.4.4 The system should send notifications to the user when he/she gets accepted for collaboration from a project.

> 1.2.4.5 The system should send notifications to the collaborators of the workspace when any application for collaboration request is sent to that workspace.

> 1.2.4.6 The system should send notifications to the collaborators of the workspace when a deadline for any assigned issue is closed.

- We can omit these requirements to reduce project complexity since it is not stated in the project description or in customer meeting 1 notes.

> 1.1.6.3 Users and guests shall be able to sort search results according to the sorting criteria as date, and number of collobarators needed.

- We can omit this requirement to reduce project complexity since it is not stated in the project description or in customer meeting 1 notes.

> 1.2.3.2 The platform shall provide definitive labels according to the user's skills.

- How the platform provides definitive labels? It is ambiguous to me. Also, requirement assumes that users have a list of skills. However, account information does not include these skills.

> 2.2.3 System objects shall be encrypted with MD5.

- Do we need that? I think it is not in project description or in customer meeting 1 notes.

> 2.2.4 System shall be backed up to AWS at the end of each day.

- Do we need that? I think it is not in project description or in customer meeting 1 notes. Also, isn't AWS is very specific? Maybe we can generalize it.

**Comment by oykuyilmaz1** [comment]
## 1 Functional Requirements
#### 1.1.1 Guests and Registration   
> 1.1.1.6 Guests shall be able to see trending projects.
* This is not given in the project description
#### 1.1.3 User Follow & Rating 
* We may not have public/private profiles but public private posts as suggested in the description.
> 1.1.3.5 Users shall be able to report another user in case of an inappropriate behavior or content.
* Since we do not have an admin type of user we may not allow users to report others.
#### 1.1.4 Permissions in Projects  
> 1.1.4.8 Collaborators of a workspace shall be able to edit editable files.
> 1.1.4.12 Collaborators shall be able to create, close and reopen issues and assign any collaborator.The definition of the issue can be found under the Glossary part. 
* I am not sure if these are required or not, we may discuss that in the meeting
#### 1.1.5 Profile Management   
> 1.1.5.2 Users shall be able to set their profiles as either public or private.
> 1.1.5.6 Users shall be able to mute all of the notifications.
> 1.1.5.7 Users shall be able to view sections as followers, comments, ratings, photo, name and e-mail in a profile.
### 1.2 System Requirements   
#### 1.2.1 System   
> 1.2.1.1 System shall provide a site map to navigate the users.
* This should not be a requirement.
#### 1.2.3 Recommendation  
> 1.2.3.4 Recommendation system shall recommend appropriate Users for the projects which are at the Search for Collaborators State.
#### 1.2.4 Notification  
* All can be removed.
#### 1.2.6 Profile Page  
> 1.2.6.1 A profile page shall be public or private.
> 1.2.6.4 Profile page shall provide the follower information which is the number of followers, the number of followed users and links to profile pages followers and followed users.
> 1.2.6.6 A public profile page and all information provided (described in 1.2.6.3, 1.2.6.4, 1.2.6.5) shall be able to be viewed by any user in the system.

> 1.2.6.7 A private profile page and all information provided (described in 1.2.6.3, 1.2.6.4, 1.2.6.5) shall be able to be viewed by only the followers of the owner of the profile page.

**Comment by HUmutOzdemir** [comment]
These are my thoughts about our project requirements

> 1.1.1.6 Guests shall be able to see trending projects.

Whe can change `shall` with `should`. Because it is easy to implement and it is a good feature. If we have time, I think we can implement it.

> 1.1.5.6 Users shall be able to mute all of the notifications.

I think we have to discuss about whether we must implement a notification system or not. If we implement such a system, I think this might be basic notification system.

> 1.2.1.1 System shall provide a site map to navigate the users.

I think we have to remove this. Because it is not a requirement.

> 1.2.1.5 System shall provide profile recommendations for new people to follow.

I am not sure about this feature was explained in the project PDF or customer meeting. As I can remember, system will make 2 types of recommendations which are a workspace to user and a user to workspace.

> 1.2.1.6 The home page shall provide workspace recommendations for Users which are at Search for Collaborators State according to the requirements explained in 1.2.4.

We can remove the home page part. `System shall provide ...`

> 1.2.4 Notification System

As I stated above, I think we should discuss the functionality of notification system.

**Comment by hilal-demir** [comment]
I think we can remove/change these requirements
1.1.3.5 Users shall be able to report another user in case of an inappropriate behavior or content.
1.1.4.14 Collaborators shall be able to change the state of the workspace.
`collaborator editing requirements can be problematic`
1.1.5.6 Users shall be able to mute all of the notifications.
1.1.5.7 Users shall be able to view sections as followers, comments, ratings, photo, name and e-mail in a profile.
1.1.6.3 Users and guests shall be able to sort search results according to the sorting criteria as date, and number of collobarators needed.
1.2.1.1 System shall provide a site map to navigate the users.
1.2.1.5 System shall provide profile recommendations for new people to follow.
1.2.3.4 Recommendation system shall recommend appropriate Users for the projects which are at the Search for Collaborators State.
1.2.4 Notification 
`easier system can be thought`
2.2.3 System objects shall be encrypted with MD5.
2.2.4 System shall be backed up to AWS at the end of each day.
2.3.6 Mobile Browsers shall redirect to the mobile application.

**Comment by ahmetdadak** [comment]
There is not a profile picture feature in the description.

> 1.1.1.1 Guests shall be able to register by providing account information which includes name, surname, e-mail, and optionally affinities, **profile photo**, past research, ResearchGate, and Google Scholar accounts.
> 1.1.5.1 Users shall be able to edit their account information which includes name, surname, e-mail, affinities, **profile photo**, research, ResearchGate and Google Scholar accounts.
> 1.2.6.5 Profile page shall provide account information which includes name, surname, e-mail certainly and affilities, **profile photo**, research, ResearchGate and Google Scholar accounts if these information is provided to the system.
> 1.1.5.7 Users shall be able to view sections as followers, comments, ratings, **photo**, name and e-mail in a profile.

There is no such specification in the description. In the Customer Meeting Note's it's been said that "Users can only register with their Google Accounts". We can remove this requirement.

> 1.1.1.2 Guests shall be able to register by using their Google accounts.
> 1.1.2.2 Users shall be able to login by using their Google accounts.

I think these requirements can not be elicitated from the description.

> 1.1.1.6 Guests shall be able to see trending projects.
> 1.1.2.3 Users shall be able to reset their password if they ever forget it.
> 1.1.3.5 Users shall be able to report another user in case of an inappropriate behavior or content.
> 1.1.5.6 Users shall be able to mute all of the notifications.
> 1.1.6.3 Users and guests shall be able to sort search results according to the sorting criteria as date, and number of collobarators needed.

I think this section is redundant.

> 1.2.4 Notification

**Comment by ertbulbul** [comment]
My ideas about the requirements of the project

> 1.2.1.1 System shall provide a site map to navigate the users.

This requirement can be removed.

> 1.2.4 Notification System

Unlike my teammates, I think notification is an important and must-stay feature.

**Comment by orkana** [comment]
> 4. Collaborator: Any user working on the same workspace.

Are all collaborators equal? Is there any hierarchy? Do a professor and a lab assistant have the same permission?

For example:
> 1.1.4.5 Collaborators of the workspace shall be able to accept/reject join requests to their workspaces.
> 1.1.4.12 Collaborators shall be able to create, close and reopen issues and assign any collaborator.The definition of the issue can be found under the Glossary part.
> 1.1.4.14 Collaborators shall be able to change the state of the workspace.

-------------

> 2.2.4 System shall be backed up to AWS at the end of each day.

When is the end of the day? Which time zone?

**Comment by HUmutOzdemir** [comment]
I made following changes on the project requiremens after our meeting at Friday @19.00.

> **6. Editable Files:** Markdown files(.md), any code file(.c,.py,.cpp,.java,.js,.m), txt files, .tex files

.etc part is removed.

> 1.1.1.1 Guests shall be able to register by providing account information which includes name, surname, e-mail, affinities and optionally profile photo, past research, ResearchGate, and Google Scholar accounts.

Affinity is not an optionaly information to register.

> 1.1.1.2 Guests should be able to register by using their Google accounts.

Shall is changed to should.

> 1.1.4.8 Collaborators of a workspace should be able to edit editable files.

`shall` is changed to `should`

> 1.1.1.6 Guests should be able to see trending projects.

Shall is changed to should.

> 1.2.1.4 System shall provide workspace recommendations for Users which are at Search for Collaborators State according to the requirements explained in 1.2.4.

`The home page` is changed to `System`

> 1.1.6.3 Users and guests shall be able to sort search results of workspaces according to the sorting criteria as date, and number of collaborators needed, alphabetical order.

 > 1.1.6.4 Users and guests shall be able to sort search results of upcoming events according to the sorting criteria as date, alphabetical order.

 > 1.1.6.5 Users and guests shall be able to sort search results of users according to the sorting criteria as alphabetical order.

These 3 requirements are added

Please check the changes I made in case of misunderstanding and wrong notes of mine.

**Comment by Hryurt** [comment]
Sorry for late commitment. Here is my review about the requirements.
> 1.1.1.1 Guests shall be able to register by providing account information which includes name, surname, e-mail, affinities and optionally profile photo, past research, ResearchGate, and Google Scholar accounts. 

- I think past researches is not a registering material. User can add it after registration.

> 1.1.1.6 Guests should be able to see trending projects.

- We can omit this requirement.

> 1.1.4.7 Collaborators of a workspace shall be able to upload the related materials such as editable files, plots, PDF files.

- What is the meaning of 'editable' in general context?

> 1.1.1.4 Guests shall be able to do basic & advanced search with using filters.

> 1.1.6.1 A user and a guest shall be able to search public workspaces, upcoming events, and users using keywords.

- I am not sure but these two requirement might include each other.

**Comment by uvut** [comment]
Sorry for not being able to comment in time.

Since we already discussed possible revisions with the team members at Meeting#17 and come to an agreement with the customer at Meeting#18 I have no further edition to do right now.

**Comment by HUmutOzdemir** [comment]
I updated the requirements according to the last meeting at lab session. Please check the new version of the requiremetns.
