### ISSUE TITLE
Update Use Case Diagram

### ISSUE THREAD

**Issue by oykuyilmaz1** [bounswe/bounswe2020group7#94]
Update the use case diagram after the requirements are finalized.

Deadline: 02.11.2020 @23.59

**Comment by hilal-demir** [comment]
I could not find anything to change in the diagram since the changes we made in the requirements are not in the diagram. For example: site map, recommendation structure, details of notifications and generally non-functional requirements. Please check in case of if I missed anything.

**Comment by darktheorys** [comment]
I have inspected the requirements and use case diagram. Change is not needed to apply on use case diagram. Current requirements are compatible with the use case diagram.
