### ISSUE TITLE
Update the Project Plan

### ISSUE THREAD

**Issue by oykuyilmaz1** [bounswe/bounswe2020group7#97]
Please update the project plan for the new semester after the requirements are finalized.

Deadline: 02.11.2020 @23.59

**Comment by orkana** [comment]
There are three milestones:

> Milestone 1: the revised requirements, design, and initial prototype

> Milestone 2: detailed prototype

> Final Milestone: final product deliverable

The classes end at January 20, 2021. This is about three months later. Assuming we space out the milestones equally; we should hit Milestone 1 at the end of November, Milestone 2 at the end of December and Final Milestone at the end of January.

**Comment by ahmetdadak** [comment]
I added revised versions of the project plan [here](https://github.com/bounswe/bounswe2020group7/wiki/Project-Plan). Please check whether it contains an error.

**Comment by hilal-demir** [comment]
Milestone 1: 24.11.2020
Milestone 2: 29.12.2020
Final Milestone: 19.01.2021

In our project plan, milestone 2's date seems to be 22.12.2020.

**Comment by ahmetdadak** [comment]
Yes, the dates have just explained right after I uploaded the project plan. I'll change them.

**Comment by ahmetdadak** [comment]
I've changed the project plan [here](https://github.com/bounswe/bounswe2020group7/wiki/Project-Plan).
