### ISSUE TITLE
Manage Labels

### ISSUE THREAD

**Issue by oykuyilmaz1** [bounswe/bounswe2020group7#98]
Please add or remove labels

Deadline: 02.11.2020 @23.59

**Comment by cakmadam98** [comment]
Reviewed current labels. I think we don't need to remove any label. They are still useful.
I've added 3 labels which are listed below.
- Subteam: Backend
- Subteam: Frontend 
- Subteam: Android

**Comment by ertbulbul** [comment]
I think we have a very good range of labels and content. I couldn't find any labels to be deleted. I've added just one label.

-Type: Documentation
