### ISSUE TITLE
Backend Programming Language

### ISSUE THREAD

**Issue by oykuyilmaz1** [bounswe/bounswe2020group7#99]
Comment your opinion  about the programming languages that should be used in backend. We may finalize this in our next meeting.

Deadline: 29.10.2020 @23.59

**Comment by cakmadam98** [comment]
I prefer Python as the backend programming language due to these reasons:

- Personal reason: I have more experience in Python than other programming languages.
- Readability
- Ease of implementation
- Supporting popular backend frameworks such as Flask and Django.

**Comment by HUmutOzdemir** [comment]
I prefer choosing a language that most of our group have more experience in. So, I think it will be better to choose Python as our backend programming language. Because half of our group are our newcommers, so I am not sure about which language is the most well-known. So if I am wrong about my thoughts on Python, please write some comments here.

**Comment by hilal-demir** [comment]
I prefer Java since I am most familiar with it and it comes with so many supported frameworks. But i will conform with the group's needs and choices. I am open to new ideas.

**Comment by alperendivriklioglu** [comment]
All of our group members are familiar with Python and have some experience in developing software using the language. Also, considering that the two popular and easy-to-use web frameworks such as Django and Flask are built for Python, and Python is commonly used among web developers and therefore it’s easy to find support when there is a problem, I think, Python would be the best choice for our project.

**Comment by cakmadam98** [comment]
I've researched possible backend frameworks. Like Alperen mentioned, Flask is recommended for its ease of use. Also it is used by companies such as Netflix, reddit, and Lyft. I guess we can trust it. I'm open to other alternatives also.

**Comment by hilal-demir** [comment]
Flask is okay for me too.

**Comment by HUmutOzdemir** [comment]
We concluded to use Flask.
